
# This file is automatically generated, you probably don't want to edit this

medxmyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "medxmyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            Y = NULL,
            X = NULL,
            M = NULL,
            covariates = NULL,
            R = 500,
            conf = 95,
            boot_seed = 1234, ...) {

            super$initialize(
                package="jmvmed",
                name="medxmy",
                requiresData=TRUE,
                ...)

            private$..Y <- jmvcore::OptionVariable$new(
                "Y",
                Y)
            private$..X <- jmvcore::OptionVariable$new(
                "X",
                X)
            private$..M <- jmvcore::OptionVariable$new(
                "M",
                M)
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates)
            private$..R <- jmvcore::OptionInteger$new(
                "R",
                R,
                default=500,
                min=100)
            private$..conf <- jmvcore::OptionNumber$new(
                "conf",
                conf,
                default=95,
                min=50.01,
                max=99.99)
            private$..boot_seed <- jmvcore::OptionInteger$new(
                "boot_seed",
                boot_seed,
                default=1234)

            self$.addOption(private$..Y)
            self$.addOption(private$..X)
            self$.addOption(private$..M)
            self$.addOption(private$..covariates)
            self$.addOption(private$..R)
            self$.addOption(private$..conf)
            self$.addOption(private$..boot_seed)
        }),
    active = list(
        Y = function() private$..Y$value,
        X = function() private$..X$value,
        M = function() private$..M$value,
        covariates = function() private$..covariates$value,
        R = function() private$..R$value,
        conf = function() private$..conf$value,
        boot_seed = function() private$..boot_seed$value),
    private = list(
        ..Y = NA,
        ..X = NA,
        ..M = NA,
        ..covariates = NA,
        ..R = NA,
        ..conf = NA,
        ..boot_seed = NA)
)

medxmyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "medxmyResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        basic = function() private$.items[["basic"]],
        mmodel = function() private$.items[["mmodel"]],
        ymodel = function() private$.items[["ymodel"]],
        rsq = function() private$.items[["rsq"]],
        indirect = function() private$.items[["indirect"]],
        plotustd = function() private$.items[["plotustd"]],
        qqustd = function() private$.items[["qqustd"]],
        plotstd = function() private$.items[["plotstd"]],
        qqstd = function() private$.items[["qqstd"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mediation Analysis (X to M to Y)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Mediation Analysis (X to M to Y)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="basic",
                title="Analysis Information",
                rows=7,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="data", 
                        `title`="Content", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mmodel",
                title="Predict M by X and covariate(s)",
                rows=1,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="coef_ustd", 
                        `title`="B", 
                        `type`="number"),
                    list(
                        `name`="coef_std", 
                        `title`="beta", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="S.E. (B)", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ymodel",
                title="Predict Y by M, X, and covariate(s)",
                rows=1,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="coef_ustd", 
                        `title`="B", 
                        `type`="number"),
                    list(
                        `name`="coef_std", 
                        `title`="beta", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="S.E. (B)", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rsq",
                title="Model R-squares",
                rows=2,
                columns=list(
                    list(
                        `name`="model", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="rsq", 
                        `title`="R-squared", 
                        `type`="number"),
                    list(
                        `name`="adjrsq", 
                        `title`="Adjusted R-squared", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df1", 
                        `type`="integer"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="integer"),
                    list(
                        `name`="f", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="indirect",
                title="Indirect Effect Estimates and Nonparametric Bootstrap Percentile Confidence Intervals",
                rows=2,
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="lb", 
                        `title`="Lower Limit", 
                        `type`="number"),
                    list(
                        `name`="ub", 
                        `title`="Upper Limit", 
                        `type`="number"),
                    list(
                        `name`="lvl", 
                        `title`="Level (%)", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotustd",
                title="Plot of Bootstrap Indirect Effect Estimates - Unstandardized",
                width=400,
                height=400,
                renderFun=".plotustd"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqustd",
                title="Normal QQ Plot of Bootstrap Indirect Effect Estimates - Unstandardized",
                width=400,
                height=400,
                renderFun=".qqustd"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotstd",
                title="Plot of Bootstrap Indirect Effect Estimates - Standardized",
                width=400,
                height=400,
                renderFun=".plotstd"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqstd",
                title="Normal QQ Plot of Bootstrap Indirect Effect Estimates - Standardized",
                width=400,
                height=400,
                renderFun=".qqstd"))}))

medxmyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "medxmyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvmed",
                name = "medxmy",
                version = c(0,0,1),
                options = options,
                results = medxmyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mediation Analysis (X to M to Y)
#'
#' 
#' @param data .
#' @param Y .
#' @param X .
#' @param M .
#' @param covariates .
#' @param R .
#' @param conf .
#' @param boot_seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$basic} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mmodel} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ymodel} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rsq} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$indirect} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotustd} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$qqustd} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotstd} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$qqstd} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$basic$asDF}
#'
#' \code{as.data.frame(results$basic)}
#'
#' @export
medxmy <- function(
    data,
    Y,
    X,
    M,
    covariates,
    R = 500,
    conf = 95,
    boot_seed = 1234) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("medxmy requires jmvcore to be installed (restart may be required)")

    if ( ! missing(Y)) Y <- jmvcore::resolveQuo(jmvcore::enquo(Y))
    if ( ! missing(X)) X <- jmvcore::resolveQuo(jmvcore::enquo(X))
    if ( ! missing(M)) M <- jmvcore::resolveQuo(jmvcore::enquo(M))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(Y), Y, NULL),
            `if`( ! missing(X), X, NULL),
            `if`( ! missing(M), M, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- medxmyOptions$new(
        Y = Y,
        X = X,
        M = M,
        covariates = covariates,
        R = R,
        conf = conf,
        boot_seed = boot_seed)

    analysis <- medxmyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

