
# This file is automatically generated, you probably don't want to edit this

medxmyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "medxmyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            m = NULL,
            covariates = NULL,
            R = 500,
            conf = 0.95,
            boot_seed = NULL, ...) {

            super$initialize(
                package="jmvmed",
                name="medxmy",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..m <- jmvcore::OptionVariable$new(
                "m",
                m)
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates)
            private$..R <- jmvcore::OptionInteger$new(
                "R",
                R,
                default=500,
                min=100)
            private$..conf <- jmvcore::OptionNumber$new(
                "conf",
                conf,
                default=0.95,
                min=0.5001,
                max=0.9999)
            private$..boot_seed <- jmvcore::OptionInteger$new(
                "boot_seed",
                boot_seed)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..m)
            self$.addOption(private$..covariates)
            self$.addOption(private$..R)
            self$.addOption(private$..conf)
            self$.addOption(private$..boot_seed)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        m = function() private$..m$value,
        covariates = function() private$..covariates$value,
        R = function() private$..R$value,
        conf = function() private$..conf$value,
        boot_seed = function() private$..boot_seed$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..m = NA,
        ..covariates = NA,
        ..R = NA,
        ..conf = NA,
        ..boot_seed = NA)
)

medxmyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "medxmyResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        mmodel = function() private$.items[["mmodel"]],
        ymodel = function() private$.items[["ymodel"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mediation Analysis (X to M to Y)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Mediation Analysis (X to M to Y)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mmodel",
                title="Predict M by X and covariates",
                rows=1,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="coef_ustd", 
                        `title`="B", 
                        `type`="number"),
                    list(
                        `name`="coef_std", 
                        `title`="beta", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ymodel",
                title="Predict Y by M, X, and covariates",
                rows=1,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="coef_ustd", 
                        `title`="B", 
                        `type`="number"),
                    list(
                        `name`="coef_std", 
                        `title`="beta", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pvalue"))))}))

medxmyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "medxmyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvmed",
                name = "medxmy",
                version = c(0,0,1),
                options = options,
                results = medxmyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mediation Analysis (X to M to Y)
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param m .
#' @param covariates .
#' @param R .
#' @param conf .
#' @param boot_seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mmodel} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ymodel} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mmodel$asDF}
#'
#' \code{as.data.frame(results$mmodel)}
#'
#' @export
medxmy <- function(
    data,
    x,
    y,
    m,
    covariates,
    R = 500,
    conf = 0.95,
    boot_seed) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("medxmy requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if ( ! missing(m)) m <- jmvcore::resolveQuo(jmvcore::enquo(m))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL),
            `if`( ! missing(m), m, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- medxmyOptions$new(
        x = x,
        y = y,
        m = m,
        covariates = covariates,
        R = R,
        conf = conf,
        boot_seed = boot_seed)

    analysis <- medxmyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

